config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users

  unauthenticated do
    root to: "main#index", as: :unauthenticated_root
  end

  authenticated do
    root to: "discussions#index"
  end

  resources :discussions do
    resources :posts, only: [:create, :edit, :update, :show, :destroy], module: :discussions

    collection do
      get "category/:id", to: "categories/discussions#index", as: :category
    end

    resources :notifications, only: :create, module: :discussions


  end

  resources :notifications, only: :index do
    collection do
      post "/mark_as_read", to: "notifications#read_all", as: :read
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount Attractor::Rails::Engine, at: "/attractor" if Rails.env.development?
end

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info mb-4" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning mb-4" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Hotwire Forums", root_path, class:  "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Discussions", discussions_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Notifications", notifications_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to Current.user.username, edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
        <% end%>
      </ul>
    </div>
  </div>
</nav>